export const CATEGORIE_LIST_REQUEST = "CATEGORIE_LIST_REQUEST";
export const CATEGORIE_LIST_SUCCESS = "CATEGORIE_LIST_SUCCESS";
export const CATEGORIE_LIST_FAIL = "CATEGORIE_LIST_FAIL";

export const CATEGORIE_EDIT_REQUEST = "CATEGORIE_EDIT_REQUEST";
export const CATEGORIE_EDIT_SUCCESS = "CATEGORIE_EDIT_SUCCESS";
export const CATEGORIE_EDIT_FAIL = "CATEGORIE_EDIT_FAIL";

export const CATEGORIE_CREATE_REQUEST = "CATEGORIE_CREATE_REQUEST";
export const CATEGORIE_CREATE_SUCCESS = "CATEGORIE_CREATE_SUCCESS";
export const CATEGORIE_CREATE_FAIL = "CATEGORIE_CREATE_FAIL";
export const CATEGORIE_CREATE_RESET = "CATEGORIE_CREATE_RESET";

export const CATEGORIE_UPDATE_REQUEST = "CATEGORIE_UPDATE_REQUEST";
export const CATEGORIE_UPDATE_SUCCESS = "CATEGORIE_UPDATE_SUCCESS";
export const CATEGORIE_UPDATE_FAIL = "CATEGORIE_UPDATE_FAIL";
export const CATEGORIE_UPDATE_RESET = "CATEGORIE_UPDATE_RESET";
