export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL";

export const ORDERS_DELIVERED_REQUEST = "ORDERS_DELIVERED_REQUEST";
export const ORDERS_DELIVERED_SUCCESS = "ORDERS_DELIVERED_SUCCESS";
export const ORDERS_DELIVERED_FAIL = "ORDERS_DELIVERED_FAIL";
export const ORDERS_DELIVERED_RESET = "ORDERS_DELIVERED_RESET";
