export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL";

export const ORDERS_DETAILS_REQUEST = "ORDERS_DETAILS_REQUEST";
export const ORDERS_DETAILS_SUCCESS = "ORDERS_DETAILS_SUCCESS";
export const ORDERS_DETAILS_FAIL = "ORDERS_DETAILS_FAIL";
